### ISSUE TITLE
Fundamental Security Issue

### ISSUE THREAD

**Issue by danielsmc** [devidw/tabgod#1]
Defining window.tabgod() doesn't just mean you can call it from devtools. It means that any JavaScript running on the page can call it. This, of course, completely destroys the same-origin policy that is central to browser security. If this is somehow the intended behavior, there should be a very prominent warning not to install this except in specialized development environments.

**Comment by devidw** [comment]
I was only thinking from the development perspective, but not about the consequences this would have with every user having that api under the same name in the global scope - you're absolutely right.

https://github.com/devidw/tabgod/commit/0627531dca19a1d45efa6784223e33c5ee951f31 moves the api from the global function to an options page and dev tools panel ui, instead of using external message passing its creating a port between only the extension and the service worker and not the user world anymore.
